version: "3.8"
services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    tty: true
    stdin_open: true
    ports:
      - 4000:4000
    volumes:
      - .:/code
